[build]
  base = "studio"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  API_URL = "https://api.indianopinions.com"
  NEXT_PUBLIC_API_URL = "https://api.indianopinions.com"
  NEXT_PUBLIC_ADMIN_URL = "https://admin.indianopinions.com/admin"

[[redirects]]
  from = "/admin/login"
  to = "/sign-in"
  status = 302

[[plugins]]
  package = "@netlify/plugin-nextjs"
