
"use client";

import React, { useState } from 'react';
import { summarizeArticle } from '@/ai/flows/summarize-article-flow';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles, Loader2, Quote } from 'lucide-react';

interface IntelligenceBriefingProps {
  content: string;
}

export function IntelligenceBriefing({ content }: IntelligenceBriefingProps) {
  const [briefing, setBriefing] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleGenerate = async () => {
    setIsLoading(true);
    try {
      const result = await summarizeArticle({ articleContent: content });
      setBriefing(result.briefing);
    } catch (error) {
      console.error('Failed to generate briefing:', error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card className="bg-secondary border-none shadow-sm my-12 overflow-hidden">
      <div className="h-1 bg-primary w-full" />
      <CardHeader className="flex flex-row items-center justify-between pb-2">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" strokeWidth={1.5} />
          <CardTitle className="text-sm font-bold uppercase tracking-[0.2em]">Intelligence Briefing</CardTitle>
        </div>
        {!briefing && !isLoading && (
          <Button 
            variant="ghost" 
            size="sm" 
            onClick={handleGenerate}
            className="text-[10px] uppercase font-bold tracking-widest h-8"
          >
            Generate Briefing
          </Button>
        )}
      </CardHeader>
      <CardContent className="pt-4">
        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-8 gap-4">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            <p className="text-xs font-medium uppercase tracking-widest text-muted-foreground">Analysing core insights...</p>
          </div>
        ) : briefing ? (
          <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2 duration-700">
            <p className="text-base leading-relaxed font-body italic text-muted-foreground pl-4 border-l-2 border-primary">
              "{briefing}"
            </p>
            <p className="text-[10px] font-bold uppercase tracking-widest text-accent text-right">
              Generated by AI Editorial Assistant
            </p>
          </div>
        ) : (
          <p className="text-sm text-muted-foreground italic leading-relaxed">
            Busy professional? Generate a 60-second actionable briefing of this essay using our proprietary Intelligence Engine.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
